import { expect, test } from '@playwright/test'
import { api, createStudent, createTeacher, loginUi, mailCode, PASSWORD } from './helpers'

test('E2E-01 학생 로그인 → 홈 → 오늘의 숙제 → 학습 화면 이동 → 숙제 완료', async ({ page }) => {
  const student = await createStudent('homework', '숙제학생')
  const teacher = await createTeacher('homework-t', '숙제선생님')
  await api('POST', '/api/v1/teachers/me/students', { studentId: student.studentId, name: student.name }, teacher.token)
  const due = new Date(Date.now() + 9 * 3600_000 + 3 * 86400_000).toISOString().slice(0, 10)
  await api('POST', '/api/v1/teachers/me/homeworks', { studentId: student.studentId, title: 'ㄹ 발음 5번 말하기', type: '발음', dueDate: due, targetMinutes: 10 }, teacher.token)

  await loginUi(page, student.email)
  await expect(page.getByText('숙제학생 학생!')).toBeVisible()
  await expect(page.getByText('완료 0 / 1')).toBeVisible()
  await page.getByRole('button', { name: /ㄹ 발음 5번 말하기/ }).click()
  await expect(page.getByText('숙제하기')).toBeVisible()
  await page.getByRole('button', { name: '연습하러 가기' }).click()
  await expect(page.getByRole('button', { name: /단어 말하기/ })).toBeVisible()
  await page.goto('/student')
  await page.getByRole('region', { name: '오늘의 숙제' }).getByRole('button', { name: '전체 보기' }).click()
  await page.getByRole('button', { name: '완료', exact: true }).click()
  await expect(page.getByText('남은 숙제가 없어요')).toBeVisible()
  const homeworks = await api<{ content?: { done: boolean }[] } | { done: boolean }[]>('GET', '/api/v1/students/me/homeworks', undefined, student.token)
  const list = Array.isArray(homeworks) ? homeworks : homeworks.content ?? []
  expect(list.every((item) => item.done)).toBe(true)
})

test('E2E-10 로그아웃 → 보호된 화면 재접근 시 로그인 요구', async ({ page }) => {
  const student = await createStudent('logout', '로그아웃학생')
  await loginUi(page, student.email)
  await page.goto('/student/mypage')
  await page.getByRole('button', { name: '로그아웃' }).click()
  await page.waitForURL((url) => url.pathname === '/')
  await page.goto('/student/history')
  await page.waitForURL((url) => !url.pathname.startsWith('/student'))
  expect(await page.evaluate(() => window.sessionStorage.getItem('chatterland.accessToken'))).toBeNull()
  // 학생 계정으로 선생님 화면에 들어가면 학생 홈으로 돌려보낸다.
  await loginUi(page, student.email)
  await page.goto('/teacher')
  await page.waitForURL(/\/student/)
})

test('AUTH-E2E 로그인 실패·역할 불일치·회원가입 검증', async ({ page }) => {
  const student = await createStudent('login', '로그인학생')
  await page.goto('/login')
  await page.locator('#login-email').fill(student.email)
  await page.locator('#login-password').fill('Wrong-Password-1')
  await page.locator('form').getByRole('button', { name: '로그인' }).click()
  await expect(page.getByText('이메일 또는 비밀번호를 확인해 주세요.')).toBeVisible()
  await page.getByRole('tab', { name: /선생님/ }).click()
  await page.locator('#login-password').fill(PASSWORD)
  await page.locator('form').getByRole('button', { name: '로그인' }).click()
  await expect(page.getByText(/선택한 선생님 계정이 아닙니다/)).toBeVisible()
  await expect(page).toHaveURL(/\/login/)

  await page.goto('/signup')
  await page.getByRole('button', { name: '회원가입' }).click()
  await expect(page.getByText('이름을 입력해 주세요.').first()).toBeVisible()
  await expect(page.getByText('개인정보 수집·이용(필수)에 동의해 주세요.')).toBeVisible()
})

test('AUTH-E2E 마이크 권한 거부 → 안내 후 다시 시도 가능', async ({ browser }) => {
  const student = await createStudent('micdeny', '마이크학생')
  const context = await browser.newContext()
  const page = await context.newPage()
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: { getUserMedia: () => Promise.reject(new DOMException('denied', 'NotAllowedError')) } })
  })
  await loginUi(page, student.email)
  await page.goto('/student/practice')
  await page.getByRole('button', { name: /단어 말하기/ }).click()
  await page.getByRole('button', { name: /발음/ }).first().click()
  await page.getByRole('button', { name: /ㄹ 발음/ }).first().click()
  await page.getByRole('button', { name: '녹음 시작' }).click()
  await expect(page.getByText(/마이크 권한이 거부되었어요/)).toBeVisible()
  await expect(page.getByRole('button', { name: '녹음 시작' })).toBeEnabled()
})

test('AUTH-E2E 아이디 찾기 → 비밀번호 재설정(실제 메일) → 새 비밀번호 로그인', async ({ page }) => {
  const teacher = await createTeacher('reset', '재설정선생님')
  await page.goto('/find-id')
  await page.getByRole('tab', { name: /선생님/ }).click()
  await page.getByRole('textbox', { name: /이름/ }).fill('재설정선생님')
  await page.getByRole('combobox', { name: /언어재활센터/ }).selectOption('1')
  await page.getByRole('button', { name: '아이디 찾기' }).click()
  await expect(page.getByText('가입된 이메일')).toBeVisible()
  await expect(page.getByText(teacher.email)).toHaveCount(0)

  await page.goto('/reset-password')
  await page.getByRole('textbox', { name: /가입한 이메일/ }).fill(teacher.email)
  await page.getByRole('button', { name: '인증 코드 받기' }).click()
  await expect(page.getByRole('textbox', { name: /인증 코드/ })).toBeVisible()
  const code = await mailCode(teacher.email)
  await page.getByRole('textbox', { name: /인증 코드/ }).fill('000000' === code ? '111111' : '000000')
  await page.getByRole('button', { name: '인증하기' }).click()
  await expect(page.getByText(/인증 코드가 올바르지 않아요. \(남은 시도 4회\)/)).toBeVisible()
  await page.getByRole('textbox', { name: /인증 코드/ }).fill(code)
  await page.getByRole('button', { name: '인증하기' }).click()
  await page.locator('input[type="password"]').nth(0).fill('NewPassword!9')
  await page.locator('input[type="password"]').nth(1).fill('NewPassword!9')
  await page.getByRole('button', { name: '비밀번호 변경' }).click()
  await expect(page.getByText('비밀번호를 변경했어요')).toBeVisible()
  const login = await fetch('http://localhost:8080/api/v1/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: teacher.email, password: 'NewPassword!9' }) })
  expect(login.status).toBe(200)
})
